// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EntryMeta struct {
	Term                 *int64     `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	Type                 *EntryType `protobuf:"varint,2,req,name=type,enum=rpc.EntryType" json:"type,omitempty"`
	Peers                []string   `protobuf:"bytes,3,rep,name=peers" json:"peers,omitempty"`
	DataLen              *int64     `protobuf:"varint,4,opt,name=data_len,json=dataLen" json:"data_len,omitempty"`
	OldPeers             []string   `protobuf:"bytes,5,rep,name=old_peers,json=oldPeers" json:"old_peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EntryMeta) Reset()         { *m = EntryMeta{} }
func (m *EntryMeta) String() string { return proto.CompactTextString(m) }
func (*EntryMeta) ProtoMessage()    {}
func (*EntryMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9874a201429861e, []int{0}
}

func (m *EntryMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryMeta.Unmarshal(m, b)
}
func (m *EntryMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryMeta.Marshal(b, m, deterministic)
}
func (m *EntryMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryMeta.Merge(m, src)
}
func (m *EntryMeta) XXX_Size() int {
	return xxx_messageInfo_EntryMeta.Size(m)
}
func (m *EntryMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryMeta.DiscardUnknown(m)
}

var xxx_messageInfo_EntryMeta proto.InternalMessageInfo

func (m *EntryMeta) GetTerm() int64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *EntryMeta) GetType() EntryType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return EntryType_ENTRY_TYPE_UNKNOWN
}

func (m *EntryMeta) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *EntryMeta) GetDataLen() int64 {
	if m != nil && m.DataLen != nil {
		return *m.DataLen
	}
	return 0
}

func (m *EntryMeta) GetOldPeers() []string {
	if m != nil {
		return m.OldPeers
	}
	return nil
}

type RequestVoteRequest struct {
	GroupId              *string  `protobuf:"bytes,1,req,name=group_id,json=groupId" json:"group_id,omitempty"`
	ServerId             *string  `protobuf:"bytes,2,req,name=server_id,json=serverId" json:"server_id,omitempty"`
	PeerId               *string  `protobuf:"bytes,3,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	Term                 *int64   `protobuf:"varint,4,req,name=term" json:"term,omitempty"`
	PrevLogTerm          *int64   `protobuf:"varint,5,req,name=prev_log_term,json=prevLogTerm" json:"prev_log_term,omitempty"`
	PrevLogIndex         *int64   `protobuf:"varint,6,req,name=prev_log_index,json=prevLogIndex" json:"prev_log_index,omitempty"`
	PreVote              *bool    `protobuf:"varint,7,req,name=pre_vote,json=preVote" json:"pre_vote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteRequest) Reset()         { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()    {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9874a201429861e, []int{1}
}

func (m *RequestVoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteRequest.Unmarshal(m, b)
}
func (m *RequestVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteRequest.Marshal(b, m, deterministic)
}
func (m *RequestVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteRequest.Merge(m, src)
}
func (m *RequestVoteRequest) XXX_Size() int {
	return xxx_messageInfo_RequestVoteRequest.Size(m)
}
func (m *RequestVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteRequest proto.InternalMessageInfo

func (m *RequestVoteRequest) GetGroupId() string {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return ""
}

func (m *RequestVoteRequest) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

func (m *RequestVoteRequest) GetPeerId() string {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return ""
}

func (m *RequestVoteRequest) GetTerm() int64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetPrevLogTerm() int64 {
	if m != nil && m.PrevLogTerm != nil {
		return *m.PrevLogTerm
	}
	return 0
}

func (m *RequestVoteRequest) GetPrevLogIndex() int64 {
	if m != nil && m.PrevLogIndex != nil {
		return *m.PrevLogIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetPreVote() bool {
	if m != nil && m.PreVote != nil {
		return *m.PreVote
	}
	return false
}

type RequestVoteResponse struct {
	Term                 *int64   `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	Granted              *bool    `protobuf:"varint,2,req,name=granted" json:"granted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteResponse) Reset()         { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()    {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9874a201429861e, []int{2}
}

func (m *RequestVoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteResponse.Unmarshal(m, b)
}
func (m *RequestVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteResponse.Marshal(b, m, deterministic)
}
func (m *RequestVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteResponse.Merge(m, src)
}
func (m *RequestVoteResponse) XXX_Size() int {
	return xxx_messageInfo_RequestVoteResponse.Size(m)
}
func (m *RequestVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteResponse proto.InternalMessageInfo

func (m *RequestVoteResponse) GetTerm() int64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *RequestVoteResponse) GetGranted() bool {
	if m != nil && m.Granted != nil {
		return *m.Granted
	}
	return false
}

func init() {
	proto.RegisterType((*EntryMeta)(nil), "rpc.EntryMeta")
	proto.RegisterType((*RequestVoteRequest)(nil), "rpc.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "rpc.RequestVoteResponse")
}

func init() {
	proto.RegisterFile("rpc/rpc.proto", fileDescriptor_d9874a201429861e)
}

var fileDescriptor_d9874a201429861e = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcd, 0x6a, 0xe3, 0x30,
	0x14, 0x85, 0xf1, 0x4f, 0x62, 0x5b, 0x99, 0x78, 0xa1, 0x19, 0x88, 0x26, 0xb3, 0x31, 0x66, 0x16,
	0x5e, 0x65, 0x86, 0x3c, 0x40, 0x17, 0x2d, 0x5d, 0x18, 0x52, 0x28, 0x6a, 0xe8, 0xd6, 0x18, 0xeb,
	0xd6, 0x04, 0x1c, 0x4b, 0xbd, 0x56, 0x4c, 0xf3, 0x18, 0x79, 0xc1, 0x3e, 0x4b, 0x91, 0x9c, 0xa4,
	0x84, 0x74, 0xd5, 0x9d, 0xcf, 0xf9, 0xee, 0x3d, 0xd2, 0x91, 0xc9, 0x14, 0x55, 0xf5, 0x0f, 0x55,
	0xb5, 0x50, 0x28, 0xb5, 0xa4, 0x1e, 0xaa, 0x6a, 0x1e, 0x1b, 0x0f, 0xda, 0xdd, 0x76, 0x30, 0xd3,
	0x83, 0x43, 0xa2, 0xfb, 0x56, 0xe3, 0xfe, 0x01, 0x74, 0x49, 0x29, 0xf1, 0x35, 0xe0, 0x96, 0x39,
	0x89, 0x9b, 0x79, 0xdc, 0x7e, 0xd3, 0x94, 0xf8, 0x7a, 0xaf, 0x80, 0xb9, 0x89, 0x9b, 0xc5, 0xcb,
	0x78, 0x61, 0x02, 0xed, 0xc6, 0x7a, 0xaf, 0x80, 0x5b, 0x46, 0x7f, 0x91, 0x91, 0x02, 0xc0, 0x8e,
	0x79, 0x89, 0x97, 0x45, 0x7c, 0x10, 0xf4, 0x37, 0x09, 0x45, 0xa9, 0xcb, 0xa2, 0x81, 0x96, 0xf9,
	0x89, 0x93, 0x79, 0x3c, 0x30, 0x7a, 0x05, 0x2d, 0xfd, 0x43, 0x22, 0xd9, 0x88, 0x62, 0x58, 0x1a,
	0xd9, 0xa5, 0x50, 0x36, 0xe2, 0xd1, 0xe8, 0xf4, 0xdd, 0x21, 0x94, 0xc3, 0xeb, 0x0e, 0x3a, 0xfd,
	0x2c, 0x35, 0x1c, 0x3f, 0x4d, 0x5c, 0x8d, 0x72, 0xa7, 0x8a, 0x8d, 0xb0, 0x17, 0x8c, 0x78, 0x60,
	0x75, 0x2e, 0x4c, 0x5c, 0x07, 0xd8, 0x03, 0x1a, 0xe6, 0x5a, 0x16, 0x0e, 0x46, 0x2e, 0xe8, 0x8c,
	0x04, 0xe6, 0x1c, 0x83, 0x3c, 0x8b, 0xc6, 0x46, 0xe6, 0xe2, 0xdc, 0xd6, 0xbf, 0x68, 0x3b, 0x55,
	0x08, 0x7d, 0xd1, 0xc8, 0xba, 0xb0, 0x70, 0x64, 0xe1, 0xc4, 0x98, 0x2b, 0x59, 0xaf, 0xcd, 0xcc,
	0x5f, 0x12, 0x9f, 0x67, 0x36, 0xad, 0x80, 0x37, 0x36, 0xb6, 0x43, 0x3f, 0x8e, 0x43, 0xb9, 0xf1,
	0xcc, 0x75, 0x15, 0x42, 0xd1, 0x4b, 0x0d, 0x2c, 0x48, 0xdc, 0x2c, 0xe4, 0x81, 0x42, 0x30, 0x85,
	0xd2, 0x3b, 0xf2, 0xf3, 0xa2, 0x5f, 0xa7, 0x64, 0xdb, 0xc1, 0x97, 0xaf, 0xcf, 0x48, 0x50, 0x63,
	0xd9, 0x6a, 0x18, 0x7a, 0x85, 0xfc, 0x24, 0x97, 0x07, 0x87, 0x4c, 0x78, 0xf9, 0xa2, 0x9f, 0x00,
	0xfb, 0x4d, 0x05, 0xf4, 0x86, 0x9c, 0xf2, 0xe9, 0xcc, 0xfe, 0xa4, 0xeb, 0x27, 0x9c, 0xb3, 0x6b,
	0x30, 0x9c, 0xfd, 0xdf, 0xa1, 0xb7, 0x64, 0x82, 0x9f, 0xe0, 0x5b, 0x19, 0x1f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x72, 0x18, 0x63, 0x73, 0x72, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RaftServiceClient is the client API for RaftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftServiceClient interface {
	PreVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (RaftService_PreVoteClient, error)
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (RaftService_RequestVoteClient, error)
}

type raftServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftServiceClient(cc grpc.ClientConnInterface) RaftServiceClient {
	return &raftServiceClient{cc}
}

func (c *raftServiceClient) PreVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (RaftService_PreVoteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RaftService_serviceDesc.Streams[0], "/rpc.RaftService/preVote", opts...)
	if err != nil {
		return nil, err
	}
	x := &raftServicePreVoteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RaftService_PreVoteClient interface {
	Recv() (*RequestVoteResponse, error)
	grpc.ClientStream
}

type raftServicePreVoteClient struct {
	grpc.ClientStream
}

func (x *raftServicePreVoteClient) Recv() (*RequestVoteResponse, error) {
	m := new(RequestVoteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *raftServiceClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (RaftService_RequestVoteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RaftService_serviceDesc.Streams[1], "/rpc.RaftService/requestVote", opts...)
	if err != nil {
		return nil, err
	}
	x := &raftServiceRequestVoteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RaftService_RequestVoteClient interface {
	Recv() (*RequestVoteResponse, error)
	grpc.ClientStream
}

type raftServiceRequestVoteClient struct {
	grpc.ClientStream
}

func (x *raftServiceRequestVoteClient) Recv() (*RequestVoteResponse, error) {
	m := new(RequestVoteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RaftServiceServer is the server API for RaftService service.
type RaftServiceServer interface {
	PreVote(*RequestVoteRequest, RaftService_PreVoteServer) error
	RequestVote(*RequestVoteRequest, RaftService_RequestVoteServer) error
}

// UnimplementedRaftServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRaftServiceServer struct {
}

func (*UnimplementedRaftServiceServer) PreVote(req *RequestVoteRequest, srv RaftService_PreVoteServer) error {
	return status.Errorf(codes.Unimplemented, "method PreVote not implemented")
}
func (*UnimplementedRaftServiceServer) RequestVote(req *RequestVoteRequest, srv RaftService_RequestVoteServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}

func RegisterRaftServiceServer(s *grpc.Server, srv RaftServiceServer) {
	s.RegisterService(&_RaftService_serviceDesc, srv)
}

func _RaftService_PreVote_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestVoteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RaftServiceServer).PreVote(m, &raftServicePreVoteServer{stream})
}

type RaftService_PreVoteServer interface {
	Send(*RequestVoteResponse) error
	grpc.ServerStream
}

type raftServicePreVoteServer struct {
	grpc.ServerStream
}

func (x *raftServicePreVoteServer) Send(m *RequestVoteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _RaftService_RequestVote_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestVoteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RaftServiceServer).RequestVote(m, &raftServiceRequestVoteServer{stream})
}

type RaftService_RequestVoteServer interface {
	Send(*RequestVoteResponse) error
	grpc.ServerStream
}

type raftServiceRequestVoteServer struct {
	grpc.ServerStream
}

func (x *raftServiceRequestVoteServer) Send(m *RequestVoteResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _RaftService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.RaftService",
	HandlerType: (*RaftServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "preVote",
			Handler:       _RaftService_PreVote_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "requestVote",
			Handler:       _RaftService_RequestVote_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc/rpc.proto",
}
